//AO CLICAR
//PEGAR AS INFORMAÇÕES NA CAIXA DE TEXTO
//CRIAR UM ELEMENTO PARA A LINHA TR
//CIAR OS ELEMENTOS DAS CELULAR TD
//DENTRO DOS TD É NECESSARIO ADICIONAR O CONTEUDO TEXTUAL
//AO FINAL ADICIONAR A LINHA DENTRO DA TABELA








